# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Tibber Reading Uploader
version: "1.1.0"
slug: tibber-reading-uploader
description: Uploads meter readings to Tibber
url: "https://github.com/beaTejakulator/tibber_reading_uploader/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant_api: true
startup: once
init: false
map:
  - share:rw
options:
  meter_sensor: ""
  email: ""
  password: ""
schema:
  meter_sensor: "str"
  email: "str"
  password: "str"
image: "ghcr.io/beatejakulator/{arch}-tibber-reading-uploader"
